In [1]:
import pandas as pd

In [4]:
dt=pd.read_csv("C:/Users/DELL/Downloads/archive/best-selling game consoles.csv")

In [7]:
dt.tail(10)

,Console Name,Type,Company,Released Year,Discontinuation Year,Units sold (million),Remarks
41,N-Gage,Handheld,Nokia,2003,2005,3.00,NaN
42,Sega CD,Home console add-on,Sega,1991,1996,2.24,NaN
43,ColecoVision,Home,Coleco,1982,1985,2.00,Final sales are greater than 2 million
44,Magnavox Odyssey,Home,Magnavox/Philips,1978,1975,2.00,NaN
45,PC Engine CD-ROM,Home console add-on,NEC,1988,1998,1.92,NaN
46,Atari 7800,Home,Atari,1986,1991,1.00,Final sales are greater than 1 million
47,Atari Lynx,Handheld,Atari,1989,1995,1.00,Final sales are greater than 1 million
48,Philips CD-i,Home,Philips,1990,1998,1.00,Final sales are greater than 1 million
49,Telstar,Dedicated,Coleco,1976,1978,1.00,Final sales are greater than 1 million
50,Atari 5200,Home,Atari,1982,1984,1.00,Final sales are greater than 1 million

In [8]:
dt.head()

,Console Name,Type,Company,Released Year,Discontinuation Year,Units sold (million),Remarks
0,PlayStation 2,Home,Sony,2000,2013,155.00,Final sales are greater than 155 million
1,Nintendo DS,Handheld,Nintendo,2004,2013,154.02,NaN
2,Nintendo Switch,Hybrid,Nintendo,2017,0,122.55,NaN
3,Game Boy,Handheld,Nintendo,1989,2003,64.42,The Game Boy (1989) and the Game Boy Color (19...
4,Game Boy Color,Handheld,Nintendo,1998,2003,44.06,NaN

In [14]:
pd.unique(dt['Type'])

array(['Home', 'Handheld', 'Hybrid', 'Dedicated', 'Home console add-on'],
      dtype=object)

In [15]:
dt.count()

Console Name            51
Type                    51
Company                 51
Released Year           51
Discontinuation Year    51
Units sold (million)    51
Remarks                 16
dtype: int64

In [18]:
pd.isna(dt['Remarks'])

0     False
1      True
2      True
3     False
4      True
5      True
6      True
7      True
8     False
9     False
10     True
11    False
12     True
13     True
14    False
15     True
16     True
17     True
18     True
19     True
20     True
21     True
22     True
23    False
24     True
25    False
26    False
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37    False
38     True
39     True
40     True
41     True
42     True
43    False
44     True
45     True
46    False
47    False
48    False
49    False
50    False
Name: Remarks, dtype: bool

In [30]:
lst=list(dt['Units sold (million)'])

In [31]:
lst

[155.0,
 154.02,
 122.55,
 64.42,
 44.06,
 117.2,
 102.49,
 101.63,
 87.4,
 84.0,
 81.51,
 82.0,
 75.94,
 61.91,
 58.5,
 49.1,
 43.4,
 32.93,
 30.75,
 30.0,
 30.0,
 24.0,
 21.74,
 18.5,
 13.56,
 15.0,
 13.0,
 10.62,
 10.0,
 9.26,
 9.13,
 8.0,
 6.0,
 5.28,
 4.5,
 3.56,
 3.5,
 3.4,
 3.0,
 3.0,
 3.0,
 3.0,
 2.24,
 2.0,
 2.0,
 1.92,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0]

In [33]:
import numpy as np
np.mean(lst)

35.54941176470588

In [36]:
np.sum(lst)

1813.02

In [37]:
np.max(lst)

155.0

In [39]:
np.min(lst)

1.0

In [40]:
np.median(lst)

13.56

In [42]:
Avg=np.sum(lst)/dt['Units sold (million)'].count()

In [43]:
Avg

35.54941176470588

In [46]:
dt['Type'].duplicated().count()

51

In [47]:
dt['Type'].drop_duplicates().count()

5

In [53]:
dt[['Console Name','Type','Company']]

,Console Name,Type,Company
0,PlayStation 2,Home,Sony
1,Nintendo DS,Handheld,Nintendo
2,Nintendo Switch,Hybrid,Nintendo
3,Game Boy,Handheld,Nintendo
4,Game Boy Color,Handheld,Nintendo
5,PlayStation 4,Home,Sony
6,PlayStation,Home,Sony
7,Wii,Home,Nintendo
8,PlayStation 3,Home,Sony
9,Xbox 360,Home,Microsoft
10,Game Boy Advance,Handheld,Nintendo
11,PlayStation Portable,Handheld,Sony
12,Nintendo 3DS,Handheld,Nintendo
13,NES/Famicom,Home,Nintendo
14,Xbox One,Home,Microsoft
15,SNES/Super Famicom,Home,Nintendo
16,Game & Watch,Handheld,Nintendo
17,Nintendo 64,Home,Nintendo
18,Sega Genesis/Mega Drive,Home,Sega
19,PlayStation 5,Home,Sony
20,Atari 2600,Home,Atari
21,Xbox,Home,Microsoft
22,GameCube,Home,Nintendo
23,Xbox Series X/S,Home,Microsoft
24,Wii U,Home,Nintendo
25,PlayStation Vita,Handheld,Sony
26,Sega Master System,Home,Sega
27,Sega Game Gear,Handheld,Sega
28,PC Engine/TurboGrafx-16,Home,NEC/Hudson Soft[note 6]
29,Sega Saturn,Home,Sega
30,Dreamcast,Home,Sega
31,Master System(Brazilian variants),Home,Tectoy
32,Dendy(Famiclone),Home,Micro Genius
33,Super NES Classic Edition,Dedicated,Nintendo
34,Famicom Disk System,Home console add-on,Nintendo
35,NES Classic Edition,Dedicated,Nintendo
36,WonderSwan,Handheld,Bandai
37,Sega Pico,Home,Sega
38,Color TV-Game,Dedicated,Nintendo
39,Intellivision,Home,Mattel
40,Mega Drive(Brazilian variants),Home,Tectoy
41,N-Gage,Handheld,Nokia
42,Sega CD,Home console add-on,Sega
43,ColecoVision,Home,Coleco
44,Magnavox Odyssey,Home,Magnavox/Philips
45,PC Engine CD-ROM,Home console add-on,NEC
46,Atari 7800,Home,Atari
47,Atari Lynx,Handheld,Atari
48,Philips CD-i,Home,Philips
49,Telstar,Dedicated,Coleco
50,Atari 5200,Home,Atari

In [59]:
lst.mode()[0]

AttributeError: 'list' object has no attribute 'mode'

In [60]:
dt

,Console Name,Type,Company,Released Year,Discontinuation Year,Units sold (million),Remarks
0,PlayStation 2,Home,Sony,2000,2013,155.00,Final sales are greater than 155 million
1,Nintendo DS,Handheld,Nintendo,2004,2013,154.02,NaN
2,Nintendo Switch,Hybrid,Nintendo,2017,0,122.55,NaN
3,Game Boy,Handheld,Nintendo,1989,2003,64.42,The Game Boy (1989) and the Game Boy Color (19...
4,Game Boy Color,Handheld,Nintendo,1998,2003,44.06,NaN
5,PlayStation 4,Home,Sony,2013,0,117.20,NaN
6,PlayStation,Home,Sony,1994,2006,102.49,NaN
7,Wii,Home,Nintendo,2006,2013,101.63,NaN
8,PlayStation 3,Home,Sony,2006,2017,87.40,Final sales are greater than 87.4 million
9,Xbox 360,Home,Microsoft,2005,2016,84.00,Final sales are greater than 84 million
10,Game Boy Advance,Handheld,Nintendo,2001,2010,81.51,NaN
11,PlayStation Portable,Handheld,Sony,2004,2014,82.00,Estimated between 80-82 million
12,Nintendo 3DS,Handheld,Nintendo,2011,2020,75.94,NaN
13,NES/Famicom,Home,Nintendo,1983,2003,61.91,NaN
14,Xbox One,Home,Microsoft,2013,2020,58.50,Estimated between 51-58.5 million
15,SNES/Super Famicom,Home,Nintendo,1990,2003,49.10,NaN
16,Game & Watch,Handheld,Nintendo,1980,1991,43.40,NaN
17,Nintendo 64,Home,Nintendo,1996,2002,32.93,NaN
18,Sega Genesis/Mega Drive,Home,Sega,1988,1997,30.75,NaN
19,PlayStation 5,Home,Sony,2020,0,30.00,NaN
20,Atari 2600,Home,Atari,1977,1992,30.00,NaN
21,Xbox,Home,Microsoft,2001,2009,24.00,NaN
22,GameCube,Home,Nintendo,2001,2007,21.74,NaN
23,Xbox Series X/S,Home,Microsoft,2020,0,18.50,Approximately around 18.5 million
24,Wii U,Home,Nintendo,2012,2017,13.56,NaN
25,PlayStation Vita,Handheld,Sony,2011,2019,15.00,Estimated between 10-15 million
26,Sega Master System,Home,Sega,1986,1996,13.00,Estimated between 10-13 million. Fun Fact The ...
27,Sega Game Gear,Handheld,Sega,1990,1997,10.62,NaN
28,PC Engine/TurboGrafx-16,Home,NEC/Hudson Soft[note 6],1987,1994,10.00,NaN
29,Sega Saturn,Home,Sega,1994,2000,9.26,NaN
30,Dreamcast,Home,Sega,1998,2001,9.13,NaN
31,Master System(Brazilian variants),Home,Tectoy,1989,1996,8.00,NaN
32,Dendy(Famiclone),Home,Micro Genius,1992,1998,6.00,NaN
33,Super NES Classic Edition,Dedicated,Nintendo,2017,2018,5.28,NaN
34,Famicom Disk System,Home console add-on,Nintendo,1986,1992,4.50,NaN
35,NES Classic Edition,Dedicated,Nintendo,2016,2018,3.56,NaN
36,WonderSwan,Handheld,Bandai,1999,2018,3.50,NaN
37,Sega Pico,Home,Sega,1993,1998,3.40,Final sales are greater than 3.4 million
38,Color TV-Game,Dedicated,Nintendo,1977,1980,3.00,NaN
39,Intellivision,Home,Mattel,1980,1990,3.00,NaN
40,Mega Drive(Brazilian variants),Home,Tectoy,1990,1996,3.00,NaN
41,N-Gage,Handheld,Nokia,2003,2005,3.00,NaN
42,Sega CD,Home console add-on,Sega,1991,1996,2.24,NaN
43,ColecoVision,Home,Coleco,1982,1985,2.00,Final sales are greater than 2 million
44,Magnavox Odyssey,Home,Magnavox/Philips,1978,1975,2.00,NaN
45,PC Engine CD-ROM,Home console add-on,NEC,1988,1998,1.92,NaN
46,Atari 7800,Home,Atari,1986,1991,1.00,Final sales are greater than 1 million
47,Atari Lynx,Handheld,Atari,1989,1995,1.00,Final sales are greater than 1 million
48,Philips CD-i,Home,Philips,1990,1998,1.00,Final sales are greater than 1 million
49,Telstar,Dedicated,Coleco,1976,1978,1.00,Final sales are greater than 1 million
50,Atari 5200,Home,Atari,1982,1984,1.00,Final sales are greater than 1 million

In [61]:
dt.isna()

,Console Name,Type,Company,Released Year,Discontinuation Year,Units sold (million),Remarks
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True
2,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True
5,False,False,False,False,False,False,True
6,False,False,False,False,False,False,True
7,False,False,False,False,False,False,True
8,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False
10,False,False,False,False,False,False,True
11,False,False,False,False,False,False,False
12,False,False,False,False,False,False,True
13,False,False,False,False,False,False,True
14,False,False,False,False,False,False,False
15,False,False,False,False,False,False,True
16,False,False,False,False,False,False,True
17,False,False,False,False,False,False,True
18,False,False,False,False,False,False,True
19,False,False,False,False,False,False,True
20,False,False,False,False,False,False,True
21,False,False,False,False,False,False,True
22,False,False,False,False,False,False,True
23,False,False,False,False,False,False,False
24,False,False,False,False,False,False,True
25,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False
27,False,False,False,False,False,False,True
28,False,False,False,False,False,False,True
29,False,False,False,False,False,False,True
30,False,False,False,False,False,False,True
31,False,False,False,False,False,False,True
32,False,False,False,False,False,False,True
33,False,False,False,False,False,False,True
34,False,False,False,False,False,False,True
35,False,False,False,False,False,False,True
36,False,False,False,False,False,False,True
37,False,False,False,False,False,False,False
38,False,False,False,False,False,False,True
39,False,False,False,False,False,False,True
40,False,False,False,False,False,False,True
41,False,False,False,False,False,False,True
42,False,False,False,False,False,False,True
43,False,False,False,False,False,False,False
44,False,False,False,False,False,False,True
45,False,False,False,False,False,False,True
46,False,False,False,False,False,False,False
47,False,False,False,False,False,False,False
48,False,False,False,False,False,False,False
49,False,False,False,False,False,False,False
50,False,False,False,False,False,False,False

In [65]:
dt.dropna(inplace = True)

In [66]:
dt

,Console Name,Type,Company,Released Year,Discontinuation Year,Units sold (million),Remarks
0,PlayStation 2,Home,Sony,2000,2013,155.00,Final sales are greater than 155 million
3,Game Boy,Handheld,Nintendo,1989,2003,64.42,The Game Boy (1989) and the Game Boy Color (19...
8,PlayStation 3,Home,Sony,2006,2017,87.40,Final sales are greater than 87.4 million
9,Xbox 360,Home,Microsoft,2005,2016,84.00,Final sales are greater than 84 million
11,PlayStation Portable,Handheld,Sony,2004,2014,82.00,Estimated between 80-82 million
14,Xbox One,Home,Microsoft,2013,2020,58.50,Estimated between 51-58.5 million
23,Xbox Series X/S,Home,Microsoft,2020,0,18.50,Approximately around 18.5 million
25,PlayStation Vita,Handheld,Sony,2011,2019,15.00,Estimated between 10-15 million
26,Sega Master System,Home,Sega,1986,1996,13.00,Estimated between 10-13 million. Fun Fact The ...
37,Sega Pico,Home,Sega,1993,1998,3.40,Final sales are greater than 3.4 million
43,ColecoVision,Home,Coleco,1982,1985,2.00,Final sales are greater than 2 million
46,Atari 7800,Home,Atari,1986,1991,1.00,Final sales are greater than 1 million
47,Atari Lynx,Handheld,Atari,1989,1995,1.00,Final sales are greater than 1 million
48,Philips CD-i,Home,Philips,1990,1998,1.00,Final sales are greater than 1 million
49,Telstar,Dedicated,Coleco,1976,1978,1.00,Final sales are greater than 1 million
50,Atari 5200,Home,Atari,1982,1984,1.00,Final sales are greater than 1 million